solace:
  java:
    host: tcp://mr-akw23icep.messaging.solace.cloud:20160
    msgVpn: msgvpn-akw23xjt3
    clientUsername: solace-cloud-client
    clientPassword: lm3r9s34itkaf576115br03039
    connectRetries: 1
    reconnectRetries: 5
    connectRetriesPerHost: 20 
    reconnectRetryWaitInMillis: 3000
    
twitter:
  consumerKey: UdldFlhf98ajATa9TmSbwLPGN
  consumerSecret: P2r5tKpBBtYxhpIXZ1ggWMibXwbkUcMRYcfvGJYNHPbHFabFJl
  token: 202223059-bgcaxrnHZ0rZBDwbTNNEJBYhZ4PSm66BHdCWD0aq
  secret: 3mUUdK0OL8ObegyFiqWH9R4zKOnpHeWrjm5WpVgrZIaBp

solacestream:
  topic: solace/twitter/stream
  trackTerms:
    - twitter
    - api
  